name: CI

on:
  push:
    branches:
      - 'v\d+.\d+'  # matches v<digit>.<digit>

jobs:
  ScanRepo:
    name: CI_CD_ScanRepo
    if: ${{ !(startsWith(github.event.head_commit.message, '#NORUN')) }}
    runs-on: ubuntu-latest
    permissions: # do necessaey for atuo-login cosign
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      id: CheckCode
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      id: ScanCode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        exit-code: '1'
        output: 'trivy-result.txt'
        severity: 'HIGH,CRITICAL'

    - name: Slack Notification Of Failure
      id: slack
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C062UQF9HFB'
        payload: |
          {
            "text": "From Github: Failure Workflow Notification",
            "blocks":
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "From Github: Failure Workflow Notification"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n${{github.ref}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{github.event_name}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Actions URL:*\n<https://github.com/${{github.repository}}/actions>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<https://github.com/${{github.repository}}/commit/${{github.sha}}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Scan Failed:*\nFailed trivy scan, see upload report."
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nZou Dingyang"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0286002N"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\nzouding@foxmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Git:*\nhttps://github.com/${{github.repository}}.git"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.CICD_G6_BOTTOKEN }}
        SLACK_COLOR: 'bad'

    - name: Notify Slack and upload file on Failure
      id: SendSlack
      if: failure()
      uses: MeilCli/slack-upload-file@v3
      with:
        channel_id: 'C062UQF9HFB'
        slack_token: ${{ secrets.CICD_G6_BOTTOKEN }}
        content: 'file content'
        file_path: trivy-result.txt
        file_type: 'text'
        title: 'title of file'
        initial_comment: 'post by slack-upload-file'
      env:
        # Set the HTTPS_PROXY environment variable to whatever your policy requires
        HTTPS_PROXY: ${{ secrets.CICD_G6_WEBHOOK }}

  SignFailure:
    name: CI_CD_Failure
    needs: ScanRepo
    runs-on: ubuntu-latest
    permissions: # do necessaey for atuo-login cosign
      contents: read
      id-token: write
    if:  success()
    steps:
      # necessary for docker container to know about the file.
    - name: Checkout code
      id: CheckCode
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CICD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.CICD_DOCKERHUB_PASSWORD }}

    - id: docker_meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ghcr.io/sigstore/sample-honk
        tags: type=sha,format=long

    - name: Build and Push container images
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        # Do be aware that this is where you set your path.
        context: ./fortunes
        # file: /Dockerfile
        push: true
        tags: saiwanita/cicd-test:latest
 
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
      with:
        github-token: ${{ github.token }}   

    - name: Check install!
      run: cosign version
     
    - name: Sign the images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: saiwanita/cicd-test:latest
      run: cosign sign --yes "${TAGS}@${DIGEST}"

    - name: Slack Notification Of Success
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C062UQF9HFB'
        payload: |
          {
            "text": "From Github: Success Workflow Notification",
            "blocks":
            [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "From Github: Success Workflow Notification"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n${{github.ref}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\n${{github.event_name}}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Actions URL:*\n<https://github.com/${{github.repository}}/actions>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<https://github.com/${{github.repository}}/commit/${{github.sha}}>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Scan Success*"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nZou Dingyang"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Metriculation:*\nA0286002N"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\nzouding@foxmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Git:*\nhttps://github.com/${{github.repository}}.git"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Image:*\nhttps://hub.docker.com/r/saiwanita/cicd-test"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.CICD_G6_BOTTOKEN }}