name: CI

on:
  push:
    branches:
      - 'v\d+.\d+'  # matches v<digit>.<digit>

jobs:
  ScanRepo:
    name: CI_CD_ScanRepo
    if: ${{ !(startsWith(github.event.head_commit.message, '#NORUN')) }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: CheckCode
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      id: ScanCode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-result.txt'
        severity: 'HIGH,CRITICAL'

    - name: Slack Notification Of Failure
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C062UQF9HFB'
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.CICD_G6_BOTTOKEN }}

    - name: Notify Slack and upload file on Failure
      if: steps.ScanCode.exit-code != '0'
      id: SendSlackFailure
      uses: MeilCli/slack-upload-file@v3
      with:
        channel_id: 'C062UQF9HFB'
        slack_token: ${{ secrets.CICD_G6_BOTTOKEN }}
        content: 'file content'
        file_path: trivy-result.txt
        file_type: 'text'
        title: 'title of file'
        initial_comment: 'Scan report by Zou Dingyang'
      env:
        # Set the HTTPS_PROXY environment variable to whatever your policy requires
        HTTPS_PROXY: ${{ secrets.CICD_G6_WEBHOOK }}

  SignContainer:
    name: CI_CD_SignContainer
    needs: ScanRepo
    runs-on: ubuntu-latest
    if:  needs.ScanCode.exit-code == '0'
        
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CICD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.CICD_DOCKERHUB_PASSWORD }}

    - id: docker_meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ghcr.io/sigstore/sample-honk
        tags: type=sha,format=long

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
 
    - name: Check install!
      run: cosign version
   
    - name: Build and Push container images
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        # Do be aware that this is where you set your path.
        context: .
        # file: /Dockerfile
        push: true
        tags: saiwanita/cicd-test:latest
 
    - name: Sign the images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: saiwanita/cicd-test:latest
      run: cosign sign --yes "${TAGS}@${DIGEST}"

    - name: Notify Slack of success
      id: SendSlackSuccess
      uses: MeilCli/slack-upload-file@v3
      with:
        channel_id: 'C062UQF9HFB'
        slack_token: ${{ secrets.CICD_G6_BOTTOKEN }}
        content: 'file content'
        file_path: trivy-result.txt
        file_type: 'text'
        title: 'title of file'
        initial_comment: 'post by slack-upload-file'
      env:
        # Set the HTTPS_PROXY environment variable to whatever your policy requires
        HTTPS_PROXY: ${{ secrets.CICD_G6_WEBHOOK }}

    # - name: Send custom JSON data to Slack workflow
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     payload-file-path: "./payload.json"
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.CICD_TEST_WEBHOOK }}

    # - name: Run Trivy vulnerability scanner
    #   id: ScanVulnerability
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: 'fs'
    #     input: '.'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: 'false'
    #     output: 'trivy-report.txt'
    #     severity: 'CRITICAL,HIGH'

    # - name: Post to a Slack channel via a proxy
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     payload-file-path: "./payload.json"
    #     slack-message: 'This message was sent through a proxy'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.CICD_TEST_WEBHOOK }}
    #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

