name: CI

on:
  push:
    branches:
      - 'v\d+.\d+'  # matches v<digit>.<digit>

jobs:
  build:
    name: CI_CD_Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Checkout code
      id: CheckCode
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner in repo mode
      id: ScanCode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        severity: 'HIGH,CRITICAL'

    - name: Notify Slack and upload file on Failure
      if: failure()
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: 'C062UQF9HFB'
        slack-message: 'This message was sent through a proxy'
        slack-file-path: trivy-result.txt
      env:
        SLACK_BOT_TOKEN: ${{ secrets.CICD_G6_BOTTOKEN }}
        # Set the HTTPS_PROXY environment variable to whatever your policy requires
        HTTPS_PROXY: ${{ secrets.CICD_G6_WEBHOOK }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.CICD_DOCKERHUB_USERNAME }}
        password: ${{ secrets.CICD_DOCKERHUB_PASSWORD }}

    - id: docker_meta
      uses: docker/metadata-action@v4.4.0
      with:
        images: ghcr.io/sigstore/sample-honk
        tags: type=sha,format=long

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.1.1
 
    - name: Check install!
      run: cosign version
   
    - name: Build and Push container images
      uses: docker/build-push-action@v5
      id: build-and-push
      with:
        # platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: saiwanita/cicd-test:latest
 
    - name: Sign the images with GitHub OIDC Token
      env:
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
        TAGS: saiwanita/cicd-test:latest
      run: cosign sign --yes "${TAGS}@${DIGEST}"

    # - name: Send custom JSON data to Slack workflow
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     payload-file-path: "./payload.json"
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.CICD_TEST_WEBHOOK }}

    # - name: Run Trivy vulnerability scanner
    #   id: ScanVulnerability
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: 'fs'
    #     input: '.'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: 'false'
    #     output: 'trivy-report.txt'
    #     severity: 'CRITICAL,HIGH'

    # - name: Post to a Slack channel via a proxy
    #   id: slack
    #   uses: slackapi/slack-github-action@v1.24.0
    #   with:
    #     payload-file-path: "./payload.json"
    #     slack-message: 'This message was sent through a proxy'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.CICD_TEST_WEBHOOK }}
    #     SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

